---

- name: import Datastax repo key
  rpm_key:
    state: present
    key: http://rpm.datastax.com/rpm/repo_key

- name: Add Datastax repository
  yum_repository:
    name: "datastax-ddc-{{ datastax_ddc_version }}"
    description: "datastax ddc {{ datastax_ddc_version }}"
    baseurl: "http://rpm.datastax.com/datastax-ddc/{{ datastax_ddc_version }}"
    enabled: yes
