---
# tasks file for kostyrevaa.datastax-ddc

- name: import Datastax repo key
  rpm_key:
    state: present
    key: http://rpm.datastax.com/rpm/repo_key

- name: Add Datastax repository
  yum_repository:
    name: "datastax-ddc-{{ datastax_ddc_version }}"
    description: "datastax ddc {{ datastax_ddc_version }}"
    baseurl: "http://rpm.datastax.com/datastax-ddc/{{ datastax_ddc_version }}"
    enabled: yes

- name: Install packages
  package: name={{ item }}
  with_items:
    - datastax-ddc
    - jemalloc

- name: Fix directory permissions
  file:
    path: /etc/cassandra/default.conf
    owner: "{{ datastax_ddc_cassandra_user }}"
    group: "{{ datastax_ddc_cassandra_group }}"
    mode: "{{ datastax_ddc_cassandra_conf_dir_mode }}"
    recurse: yes
    state: directory

- name: enable cassandra service
  service:
    name: cassandra
    enabled: yes

- name: start cassandra service
  service:
    name: cassandra
    state: started
  when: datastax_ddc_manage_cassandra_service
