---
# tasks file for kostyrevaa.datastax-ddc

- include: vars.yml

- include: "install-{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ datastax_ddc_packages }}"

- name: Fix directory permissions
  file:
    path: "{{ datastax_ddc_conf_dir }}"
    owner: "{{ datastax_ddc_cassandra_user }}"
    group: "{{ datastax_ddc_cassandra_group }}"
    mode: "{{ datastax_ddc_cassandra_conf_dir_mode }}"
    recurse: yes
    state: directory

- include: template.yml

- name: enable cassandra service
  service:
    name: cassandra
    enabled: "{{ datastax_ddc_enable_cassandra_service }}"

# Flush handlers now, so we avoid starting the process and then
# restarting it immediately after notifications are flushed.
- meta: flush_handlers

- name: start cassandra service
  service:
    name: cassandra
    state: started
  when: datastax_ddc_manage_cassandra_service
