---
# tasks file for kostyrevaa.datastax-ddc

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- include: "install-{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ item }}"
  with_items: "{{ datastax_ddc_packages }}"

- name: Fix directory permissions
  file:
    path: "{{ datastax_ddc_conf_dir }}"
    owner: "{{ datastax_ddc_cassandra_user }}"
    group: "{{ datastax_ddc_cassandra_group }}"
    mode: "{{ datastax_ddc_cassandra_conf_dir_mode }}"
    recurse: yes
    state: directory

- name: Update the cassandra configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ datastax_ddc_conf_dir }}/{{item}}"
    owner: "{{ datastax_ddc_cassandra_user }}"
    group: "{{ datastax_ddc_cassandra_group }}"
    mode: "{{ datastax_ddc_cassandra_conf_dir_mode }}"
  with_items:
    - "cassandra.yaml"
  notify:
    - restart cassandra
  tags:
    - cassandra-config
    - config

- name: enable cassandra service
  service:
    name: cassandra
    enabled: "{{ datastax_ddc_enable_cassandra_service }}"

- name: start cassandra service
  service:
    name: cassandra
    state: started
  when: datastax_ddc_manage_cassandra_service
